project:
  type: website

website:
  google-analytics: "G-SDG552HSPC"
  search: false
  title: "Harry Zhong"
  favicon: logo.png
  navbar:
    pinned: true
    left:
      - text: "{{<fa diagram-project>}} Projects"
        href: projects.qmd
      - text: "{{<fa calendar-check>}} Timeline"
        href: timeline.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/harry2687/
      - icon: github
        href: https://github.com/Harry2687
      - icon: envelope
        href: mailto:h.zhong2687@gmail.com

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: true